import os
import json
from datetime import datetime
from pydantic import BaseModel, Field
from langchain_core.tools import tool
import sys

# Add parent directory to path to import config_loader
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config_loader import get_workspace_dir

class WalkthroughInput(BaseModel):
    accomplishments: str = Field(..., description="Markdown formatted list of what was achieved.")
    changes_made: str = Field(..., description="Markdown formatted list of files modified and why.")
    verification_status: str = Field(..., description="Summary of verification results (e.g., 'All files passed integrity check').")

@tool(args_schema=WalkthroughInput)
def update_walkthrough(accomplishments: str, changes_made: str, verification_status: str) -> str:
    """
    Updates the persistent walkthrough.md file in the agent context.
    Use this to document progress and final results for human review.
    """
    backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    context_dir = os.path.join(backend_dir, ".agent_context")
    os.makedirs(context_dir, exist_ok=True)
    
    walkthrough_path = os.path.join(context_dir, "walkthrough.md")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# Project Walkthrough - {timestamp}

## Accomplishments
{accomplishments}

## Changes Made
{changes_made}

## Verification & Integrity
{verification_status}

---
*Generated by Agentic Framework*
"""
    
    try:
        with open(walkthrough_path, "w", encoding="utf-8") as f:
            f.write(content)
        
        from logger import log
        log.persist("WALKTHROUGH", f"Updated {walkthrough_path}")
        
        return f"Walkthrough successfully updated at {walkthrough_path}"
    except Exception as e:
        return f"Error updating walkthrough: {str(e)}"
